### ISSUE TITLE
test-related questions, understand whether you need to change the test in the testMcryptGenericMode

### ISSUE THREAD

**Issue by jhonatasfender** [phpseclib/mcrypt_compat#20]
Well I noticed that in the tests has a "Risky", and I went to look at the code:

```php
    /**
     * @dataProvider mcryptBlockModuleNameProvider
     */
    public function testMcryptGenericMode($modeName, $validMode)
    {
        if (!$validMode) {
            return;
        }
        $key = str_repeat('a', 16);
        $iv = str_repeat('b', 16);
        $plaintext = str_repeat('c', 16);
        $mcrypt = mcrypt_encrypt('rijndael-128', $key, $plaintext, $modeName, $iv);
        $compat = phpseclib_mcrypt_encrypt('rijndael-128', $key, $plaintext, $modeName, $iv);
        $this->assertEquals(bin2hex($mcrypt), bin2hex($compat));
    }
```
And you wanted to know if it's for you this way, or do you accept that you make changes to this method?

I ran the tests on my machine, and this was the displayed log of script execution:
```
$ ./vendor/bin/phpunit
PHPUnit 6.5.10 by Sebastian Bergmann and contributors.

.....................S.S.S.....................................  63 / 132 ( 47%)
.............SSS.S.SSS.SSS.SSS.S.S.S.S.S.S.S.S.S.S.S.S.S...SS.. 126 / 132 ( 95%)
.....R                                                          132 / 132 (100%)

Time: 15.28 minutes, Memory: 6.00MB

There was 1 risky test:

1) MCryptCompatTest::testMcryptGenericMode with data set #6 ('invalid-mode', false)
This test did not perform any assertions

OK, but incomplete, skipped, or risky tests!
Tests: 132, Assertions: 186, Skipped: 31, Risky: 1.
```

**Comment by terrafrost** [comment]
The goal of the test is to make sure that exceptions aren't thrown.

So there was issue # 19. It was a legit issue and yet the unit tests were passing. So I added a unit test that'd reproduce the issue. That'd fail until the issue was fixed:

https://github.com/phpseclib/mcrypt_compat/commit/2f08f6ba34c904c5b6314217e51d75aa627653a9

As predicted, that caused the unit tests to fail:

https://travis-ci.org/terrafrost/mcrypt_compat/builds/411073266

After that I added a commit to fix the issue:

https://github.com/phpseclib/mcrypt_compat/commit/7f9f0f59ad152f78a7f4f24396905fa6b50a1698

The unit tests passed after that commit:

https://travis-ci.org/terrafrost/mcrypt_compat/builds/411074657
