### ISSUE TITLE
RC6 on PHP 8.3

### ISSUE THREAD

**Issue by HASTJI** [phpseclib/mcrypt_compat#41]
Is that lib can actually decode an binary, which is encoded with RC6 cypher? In Readme there is only said about rc2, but in code I saw define of RC6 constant. So....is it viable for php 8.3?

**Comment by terrafrost** [comment]
mcrypt_compat doesn't support RC6. The constant is defined because I (probably) just defined all the constants that I was able to get definitions for on the PHP install that I was using at the time. So like when I did `echo MCRYPT_RC6_256;` I probably got some error about that constant not being defined, hence it not having a definition in lib/mcrypt.php.
